#ifndef AFFLUENCE_PROCMOUNTER_SERVICE_IPC_CLIENT_H_
#define AFFLUENCE_PROCMOUNTER_SERVICE_IPC_CLIENT_H_

int procmounter_service_ipc_client(int dir,int socket);

#endif /* AFFLUENCE_PROCMOUNTER_SERVICE_IPC_CLIENT_H_ */